server:
  port: 80
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: auth-service
          predicates:
            - Path=/auth/**                 # localhost/auth/find_all - localhost/api/v1/auth/find_all
          uri: http://localhost:7071        #localhost:7071/api/v1/auth/find_all
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: user-service
          predicates:
            - Path=/user/**
          uri: http://localhost:7072
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}


