server:
  port: 8889
spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: ${git-config-uri}
          default-label: master
          skip-ssl-validation: true
          username: ${git-username}
          password: ${git-config-password}