server:
  port: 7072
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/SocialUserDb
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secretKey: alperen
  password: alperen
